# Worshop 2.1 Numpy

1. Скачайте этот ноутбук к себе.
2. Заполните пропущенные ячейки, отвечая на заданные вопросы. Там должен быть код! (если не сказано обратное)
3. Сохраните результат в своём гитхаб репозитории.

#### Полезная литература

- http://www.numpy.org/
- https://jakevdp.github.io/PythonDataScienceHandbook/02.00-introduction-to-numpy.html
- https://docs.scipy.org/doc/numpy/user/quickstart.html

1) Импортировать numpy и написать версию

In [2]:
import numpy as np

2) Создать нулевой вектор размера 10

In [3]:
a = np.zeros(10, int)
print(a)

[0 0 0 0 0 0 0 0 0 0]


3) Создать вектор заполненный 7-ами размера 7

In [48]:
b = np.full(7, 7)
b

array([7, 7, 7, 7, 7, 7, 7])

4) Создать вектор заполненный четными числами от 10 до 100

In [29]:
c = np.array([i for i in range(10, 100) if i % 2 == 0])
print(c)

[10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48 50 52 54 56
 58 60 62 64 66 68 70 72 74 76 78 80 82 84 86 88 90 92 94 96 98]


In [41]:
tenten = np.array(range(10,100))
tenten[tenten%2==0]


array([1000,   11, 1000,   13, 1000,   15, 1000,   17, 1000,   19, 1000,
         21, 1000,   23, 1000,   25, 1000,   27, 1000,   29, 1000,   31,
       1000,   33, 1000,   35, 1000,   37, 1000,   39, 1000,   41, 1000,
         43, 1000,   45, 1000,   47, 1000,   49, 1000,   51, 1000,   53,
       1000,   55, 1000,   57, 1000,   59, 1000,   61, 1000,   63, 1000,
         65, 1000,   67, 1000,   69, 1000,   71, 1000,   73, 1000,   75,
       1000,   77, 1000,   79, 1000,   81, 1000,   83, 1000,   85, 1000,
         87, 1000,   89, 1000,   91, 1000,   93, 1000,   95, 1000,   97,
       1000,   99])

5) Создать массив случайных чисел и развернуть его задом наперёд

In [51]:
d = np.random.randint(0, 10, 10)
print(d)
d = d[::-1]
print(d)
np.flip(d,axis=0)

[8 1 8 7 1 3 7 4 1 9]
[9 1 4 7 3 1 7 8 1 8]


array([8, 1, 8, 7, 1, 3, 7, 4, 1, 9])

6) Создать двумерную матрицу размера 3 на 3, заполненную числами от 0 до 9

In [54]:
m = np.arange(0,9)
m.reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

7) Создать матрицу размера 4 на 4 с единицами на диагонали смещеной на один наверх.

In [62]:
m = np.zeros((4,4),int)

for i in range(0, np.size(m, axis = 0) - 1):
    m[i][i + 1] = 1
m

array([[0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1],
       [0, 0, 0, 0]])

In [64]:
np.eye(4, k=1)

array([[0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.]])