# Homework 2.1 Numpy

1. Скачайте этот ноутбук к себе.
2. Заполните пропущенные ячейки, отвечая на заданные вопросы. Там должен быть код! (если не сказано обратное)
3. Сохраните результат в своём гитхаб репозитории.

#### Полезная литература

- http://www.numpy.org/
- https://jakevdp.github.io/PythonDataScienceHandbook/02.00-introduction-to-numpy.html
- https://docs.scipy.org/doc/numpy/user/quickstart.html

1) Создать матрицу с числами в диапазоне от 1 до 4 по диагонали. В других ячейках матрицы должны быть семерки.

In [5]:
import numpy as np

n = np.full((4,4), 7)

for i in range(0, np.size(n, axis=0)):
    n[i][i] = i + 1
#Можно это через np.diag или n.diagonal сделать? 
print(n)


[[1 7 7 7]
 [7 2 7 7]
 [7 7 3 7]
 [7 7 7 4]]


2) Создать матрицу размера 5 на 5 заполненную чилами от 0 до 4 в строках.

In [6]:
size_w = 5
size_h = 5
n = np.array([[j for j in range(0, size_w)] for i in range(0, size_h)])
print(n)

n = np.zeros((size_w,size_h), dtype=int)
n[0::] = np.arange(size_w)
print(n)


[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]
[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


3) Создать матрицу случайных чисел размера 10 на 10 и отнять среднее по строкам из каждого элемента строки

In [7]:
n = np.random.randint(0, 100, (10, 10))

print("Before")
print(n)

print("Means")
for i in range(0 , np.size(n, axis=0)):
    mean = n[i].mean()
    print(mean)
    for j in range(0, np.size(n, axis=1)):
        n[i][j] -= mean

print("After")
print(n)

Before
[[36  4 41 31 35 14 34  0 23 69]
 [65  3 65 72 48 19 58 78 51  6]
 [40 96 56 42 79 24 41 49 42 79]
 [29 86 60 77 93 55 22 63 85 65]
 [24 15  4 91 87 93 59 75 41 91]
 [55 18 61 83 46 41 48 71 59 33]
 [33 43 10 17 52 42 37 36 42 50]
 [64 30 40  0 58 80 12 46 61 69]
 [ 0 89 30 82 79 95 39 81 61 59]
 [ 8 39 35 93 50 37  4 83 40 50]]
Means
28.7
46.5
54.8
63.5
58.0
51.5
36.2
46.0
61.5
43.9
After
[[  7 -24  12   2   6 -14   5 -28  -5  40]
 [ 18 -43  18  25   1 -27  11  31   4 -40]
 [-14  41   1 -12  24 -30 -13  -5 -12  24]
 [-34  22  -3  13  29  -8 -41   0  21   1]
 [-34 -43 -54  33  29  35   1  17 -17  33]
 [  3 -33   9  31  -5 -10  -3  19   7 -18]
 [ -3   6 -26 -19  15   5   0   0   5  13]
 [ 18 -16  -6 -46  12  34 -34   0  15  23]
 [-61  27 -31  20  17  33 -22  19   0  -2]
 [-35  -4  -8  49   6  -6 -39  39  -3   6]]


4) Создать матрицу случайных чисел размера 10 на 10 и отнять медиану по столбцам из каждого элемента столбца  

In [8]:
n = np.random.randint(0, 100, (10, 10))

print("Before")
print(n)

print("Medians")
for i in range(0 , np.size(n, axis=1)):
    median = np.median(n[:,i])    
    print(median)
    for j in range(0, np.size(n, axis=1)):
        n[j][i] -= median

print("After")
print(n)

Before
[[99 11 78 70 37 35 11 99 28 94]
 [15 28  1 51 91  4 34 99 47 75]
 [67 66 59 16 87 11 89 90 75 88]
 [43  9 46 42 84 74 51 20 74 72]
 [49 85 50 68  4 65 84 35 44 17]
 [63 86 77 83 77  8 76 38 71 11]
 [ 8 35 11 15 15  8 27 85 20 21]
 [36 87 53 86  4 23 77 30 54 67]
 [46 87 55  0 26 77 59 58 31  9]
 [44 97 93  4 80 67 54 82 26 11]]
Medians
45.0
75.5
54.0
46.5
57.0
29.0
56.5
70.0
45.5
44.0
After
[[ 54 -64  24  23 -20   6 -45  29 -17  50]
 [-30 -47 -53   4  34 -25 -22  29   1  31]
 [ 22  -9   5 -30  30 -18  32  20  29  44]
 [ -2 -66  -8  -4  27  45  -5 -50  28  28]
 [  4   9  -4  21 -53  36  27 -35  -1 -27]
 [ 18  10  23  36  20 -21  19 -32  25 -33]
 [-37 -40 -43 -31 -42 -21 -29  15 -25 -23]
 [ -9  11  -1  39 -53  -6  20 -40   8  23]
 [  1  11   1 -46 -31  48   2 -12 -14 -35]
 [ -1  21  39 -42  23  38  -2  12 -19 -33]]


5) Создать матрицу случайных чисел 5x5. Добавить к ней столбецы максимумов и минимумов по строкам. Получится матрица 5x7.  

In [9]:
n = np.random.randint(0, 10, (5, 5))

print("Before")
print(n)

max_n = np.zeros(5)
for i in range(0, np.size(n, axis=0)):
        max_n[i] = n[i].max()

n = np.hstack([n, max_n.reshape((np.size(n, axis=0), 1))])
        
min_n = np.zeros(5)
for i in range(0, np.size(n, axis=0)):
        min_n[i] = n[i].min()

n = np.hstack([n, min_n.reshape((np.size(n, axis=0), 1))])
    
print("After")
print(n) 

Before
[[6 3 3 7 6]
 [6 7 3 8 6]
 [8 9 0 4 5]
 [5 2 6 4 7]
 [0 6 0 7 9]]
After
[[6. 3. 3. 7. 6. 7. 3.]
 [6. 7. 3. 8. 6. 8. 3.]
 [8. 9. 0. 4. 5. 9. 0.]
 [5. 2. 6. 4. 7. 7. 2.]
 [0. 6. 0. 7. 9. 9. 0.]]


6) Вектор чисел от 1 до 51 преобразовать в вектор нечетных чисел и в вектор четных чисел, поменять их размерности, чтобы получились две матрица. Найти произведение этих матриц. Найти обратную матрицу эётого произведения.  

In [10]:
n = np.arange(1,51)

from numpy import matrix 
from numpy import linalg

even = n[1::2] #так видь направильно?
odd = n[::2]

print(even)
print(odd)

even = even.reshape(5,5)
odd = odd.reshape(5,5)

print(even)
print(odd)

dot = np.dot(even, odd)

print(dot)

print(np.linalg.inv(dot)) #так нельзя же найти

[ 2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48
 50]
[ 1  3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37 39 41 43 45 47
 49]
[[ 2  4  6  8 10]
 [12 14 16 18 20]
 [22 24 26 28 30]
 [32 34 36 38 40]
 [42 44 46 48 50]]
[[ 1  3  5  7  9]
 [11 13 15 17 19]
 [21 23 25 27 29]
 [31 33 35 37 39]
 [41 43 45 47 49]]
[[ 830  890  950 1010 1070]
 [1880 2040 2200 2360 2520]
 [2930 3190 3450 3710 3970]
 [3980 4340 4700 5060 5420]
 [5030 5490 5950 6410 6870]]


LinAlgError: Singular matrix

7) Создать 8x8 матрицу и заполнить её в шахматном порядке нулями и единицами. 

In [11]:
n = np.zeros((8,8), dtype=int)
n[1::2,::2] = n[::2,1::2] = 1
print(n)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]
