# Homework 2.1 Numpy

1. Скачайте этот ноутбук к себе.
2. Заполните пропущенные ячейки, отвечая на заданные вопросы. Там должен быть код! (если не сказано обратное)
3. Сохраните результат в своём гитхаб репозитории.

#### Полезная литература

- http://www.numpy.org/
- https://jakevdp.github.io/PythonDataScienceHandbook/02.00-introduction-to-numpy.html
- https://docs.scipy.org/doc/numpy/user/quickstart.html

1) Создать матрицу с числами в диапазоне от 1 до 4 по диагонали. В других ячейках матрицы должны быть семерки.

In [60]:
import numpy as np

n = np.full((4,4), 7)

for i in range(0, np.size(n, axis=0)):
    n[i][i] = i + 1
#Можно это через np.diag или n.diagonal сделать? 
print(n)


[[1 7 7 7]
 [7 2 7 7]
 [7 7 3 7]
 [7 7 7 4]]


2) Создать матрицу размера 5 на 5 заполненную чилами от 0 до 4 в строках.

In [66]:
size_w = 5
size_h = 5
n = np.array([[j for j in range(0, size_w)] for i in range(0, size_h)])
print(n)

n = np.zeros((size_w,size_h), dtype=int)
n[0::] = np.arange(size_w)
print(n)


[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]
[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


3) Создать матрицу случайных чисел размера 10 на 10 и отнять среднее по строкам из каждого элемента строки

In [27]:
n = np.random.randint(0, 100, (10, 10))

print("Before")
print(n)

print("Means")
for i in range(0 , np.size(n, axis=0)):
    mean = n[i].mean()
    print(mean)
    for j in range(0, np.size(n, axis=1)):
        n[i][j] -= mean

print("After")
print(n)

Before
[[59 62 44 23 16  3 28 84 39 72]
 [61 43 59 44 58 33 25 46 66 46]
 [34 84 91 87 23 97 71 37 11 10]
 [92 86 90 42 53 45 80 89 40 17]
 [87 29 70 53 20 78 32 80 40 53]
 [34 67  8 55 65 14 52 34 23 46]
 [47 50 88 98 95 63 84  3 78 73]
 [38 13  4 49 68  5 95 23 26 71]
 [56 78 33 64 23  5  0 16 76  0]
 [ 5 75 42  9 50 82 12 37 34 28]]
Means
43.0
48.1
54.5
63.4
54.2
39.8
67.9
39.2
35.1
37.4
After
[[ 16  19   1 -20 -27 -40 -15  41  -4  29]
 [ 12  -5  10  -4   9 -15 -23  -2  17  -2]
 [-20  29  36  32 -31  42  16 -17 -43 -44]
 [ 28  22  26 -21 -10 -18  16  25 -23 -46]
 [ 32 -25  15  -1 -34  23 -22  25 -14  -1]
 [ -5  27 -31  15  25 -25  12  -5 -16   6]
 [-20 -17  20  30  27  -4  16 -64  10   5]
 [ -1 -26 -35   9  28 -34  55 -16 -13  31]
 [ 20  42  -2  28 -12 -30 -35 -19  40 -35]
 [-32  37   4 -28  12  44 -25   0  -3  -9]]


4) Создать матрицу случайных чисел размера 10 на 10 и отнять медиану по столбцам из каждого элемента столбца  

In [34]:
n = np.random.randint(0, 100, (10, 10))

print("Before")
print(n)

print("Medians")
for i in range(0 , np.size(n, axis=1)):
    median = np.median(n[:,i])    
    print(median)
    for j in range(0, np.size(n, axis=1)):
        n[j][i] -= median

print("After")
print(n)

Before
[[48 56 83 68 34  5 66 85 63 42]
 [ 9  8 90 41 82  4 73  4 58 32]
 [23 87 12 92 66 83 75 64 68  5]
 [70  2 14 62 27 80 44 47 21 56]
 [44 41 86  0 50  3  5 16 58  8]
 [ 5 91 11 38 59 43 25 90 24 76]
 [97 44 32 88 49 76 82 37 47 17]
 [18 68 74 91 47 85 92 30 31  7]
 [66 49 68 83 54 36 79 88 94 66]
 [84 91 19 75 81 56  2  1  7 32]]
Medians
46.0
52.5
50.0
71.5
52.0
49.5
69.5
42.0
52.5
32.0
After
[[  2   3  33  -3 -18 -44  -3  43  10  10]
 [-37 -44  40 -30  30 -45   3 -38   5   0]
 [-23  34 -38  20  14  33   5  22  15 -27]
 [ 24 -50 -36  -9 -25  30 -25   5 -31  24]
 [ -2 -11  36 -71  -2 -46 -64 -26   5 -24]
 [-41  38 -39 -33   7  -6 -44  48 -28  44]
 [ 51  -8 -18  16  -3  26  12  -5  -5 -15]
 [-28  15  24  19  -5  35  22 -12 -21 -25]
 [ 20  -3  18  11   2 -13   9  46  41  34]
 [ 38  38 -31   3  29   6 -67 -41 -45   0]]


5) Создать матрицу случайных чисел 5x5. Добавить к ней столбецы максимумов и минимумов по строкам. Получится матрица 5x7.  

In [47]:
n = np.random.randint(0, 10, (5, 5))

print("Before")
print(n)

max_n = np.zeros(5)
for i in range(0, np.size(n, axis=0)):
        max_n[i] = n[i].max()

n = np.hstack([n, max_n.reshape((np.size(n, axis=0), 1))])
        
min_n = np.zeros(5)
for i in range(0, np.size(n, axis=0)):
        min_n[i] = n[i].min()

n = np.hstack([n, min_n.reshape((np.size(n, axis=0), 1))])
    
print("After")
print(n) 

Before
[[8 4 7 4 8]
 [3 3 6 7 6]
 [1 3 0 4 2]
 [2 2 3 6 0]
 [0 8 2 6 8]]
After
[[8. 4. 7. 4. 8. 8. 4.]
 [3. 3. 6. 7. 6. 7. 3.]
 [1. 3. 0. 4. 2. 4. 0.]
 [2. 2. 3. 6. 0. 6. 0.]
 [0. 8. 2. 6. 8. 8. 0.]]


6) Вектор чисел от 1 до 51 преобразовать в вектор нечетных чисел и в вектор четных чисел, поменять их размерности, чтобы получились две матрица. Найти произведение этих матриц. Найти обратную матрицу эётого произведения.  

In [89]:
n = np.arange(1,51)

from numpy import matrix 
from numpy import linalg

even = n[1::2] #так видь направильно?
odd = n[::2]

print(even)
print(odd)

even = even.reshape(5,5)
odd = odd.reshape(5,5)

print(even)
print(odd)

dot = np.dot(even, odd)

print(dot)

print(np.linalg.inv(dot)) #так нельзя же найти

[ 2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48
 50]
[ 1  3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37 39 41 43 45 47
 49]
[[ 2  4  6  8 10]
 [12 14 16 18 20]
 [22 24 26 28 30]
 [32 34 36 38 40]
 [42 44 46 48 50]]
[[ 1  3  5  7  9]
 [11 13 15 17 19]
 [21 23 25 27 29]
 [31 33 35 37 39]
 [41 43 45 47 49]]
[[ 830  890  950 1010 1070]
 [1880 2040 2200 2360 2520]
 [2930 3190 3450 3710 3970]
 [3980 4340 4700 5060 5420]
 [5030 5490 5950 6410 6870]]


LinAlgError: Singular matrix

7) Создать 8x8 матрицу и заполнить её в шахматном порядке нулями и единицами. 

In [46]:
n = np.zeros((8,8), dtype=int)
n[1::2,::2] = n[::2,1::2] = 1
print(n)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]
